# Generated by Django 5.2.7 on 2025-11-07 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('delux', 'Delux'), ('executive', 'Executive')], max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_nights', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.TextField(blank=True)),
                ('loyalty_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Guests',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('checkin_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('actual_check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_check_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('id_proof_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card')], default='aadhaar', max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='hotel.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.guest'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(default='standard', max_length=20)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('delux', 'Delux'), ('executive', 'Executive')], max_length=10)),
                ('capacity', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(default='Great')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['status', 'room_type'], name='hotel_room_status_dd86bf_idx')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room'),
        ),
    ]
